---
# From ansible-galaxy (a release tag)
#- src: adrianjuhl.thycotic_cli
#  version: 0.6.0

# From a branch from the github repo
- src: https://github.com/adrianjuhl/ansible-role-thycotic-cli
  scm: git
  version: 0.7.0-develop-switch-from-soap-to-rest-WIP-1
  name: adrianjuhl.thycotic_cli
