---
# From ansible-galaxy (a release tag)
- src: "adrianjuhl.thycotic_cli"
  version: "0.8.0"

# From a branch from the github repo
#- src: "https://github.com/adrianjuhl/ansible-role-thycotic-cli"
#  scm: "git"
#  version: "0.8.0-develop-move-script-to-dedicated-repo-WIP-1"
#  name: "adrianjuhl.thycotic_cli"
